swissmonkey-web/config/routes.rb
Rails.application.routes.draw do
  get 'subscription/summary'
  get 'notification/count'
  get 'notification/change_count'
  get 'notification/mark_read'

  get 'api_test' => 'application#api_test'

  namespace :api do
    namespace 'v1', path: 'v1.0' do # as v1.0', controller: 'v1', as: 'v1' do
      get 'dropdown/data', action: 'datasets'

      namespace :user do
        post 'signup'
        post 'login'
        post 'logout'
        post 'forgot'
        post 'reset'
        post 'validate'
        post 'deactivate'
        post 'activate'
        post 'deviceregistration', action: 'device_registration'
        post 'accept_privacy_policy'
        post 'privacy_policy_status'
      end

      namespace :job do
        post 'details/:id', action: 'details'
        post 'search'
        post 'save'
        post 'apply'
        post 'jobs'
        post 'applications'
        post 'savedjobs'
        post 'history'
      end

      namespace :profile do
        post 'save'
        post 'upload'
        post 'download'
        post 'info'
        post 'delete'
      end

      namespace :settings do
        post 'apinotifications'
        post 'update'
        post 'viewed'
      end
    end
  end

  namespace :authentications do
    get 'facebook'
    get 'google'
    get 'linkedin'
  end

  namespace :stripe do
    post 'apply_coupon'
    post 'delete_card'
    post 'check_location_payment'
  end

  resources :applicants # , only: :index
  resources :companies do
    post 'set_current_context'
  end
  resources :job_postings
  get 'profile/me' => 'profiles#me', as: 'my_profile'
  resources :profiles
  resource :account, controller: 'account' do
    get 'verify_email_change'
    post 'set_current_company/:id', action: 'set_current_company', as: 'set_current_company'
  end
  resource :subscription

  get 'super_admin' => 'super_admin#index'
  namespace :super_admin do
    resources :companies
    resources :job_postings
    resources :users
  end

  devise_for :admins
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/auth/facebook/callback' => 'authentications#facebook'
  get '/auth/google_oauth2/callback' => 'authentications#google'
  get '/auth/linkedin/callback' => 'authentications#linkedin'

  # legacy paths
  match 'publishJob/:id' => 'job_postings#publish_job', via: %i[get post]
  match 'accountSettings' => 'profile#account_settings', via: %i[get post]
  match 'alertnotification' => 'profile#alert_notification', via: %i[get post]

  root 'home#index'
end

swissmonkey-web/app/models/job_posting.rb
# == Schema Information
#
# Table name: job_postings
#
#  id                            :integer          not null, primary key
#  job_position_id               :integer
#  job_description               :text
#  closed_job_reason_id          :integer
#  skype_interview               :string(100)      default("No"), not null
#  company_id                    :integer
#  logo                          :string(250)
#  company_location_id           :integer
#  compensation_type             :string(20)
#  publication_status            :string(20)
#  years_experience              :string(20)
#  job_type                      :string(30)
#  payment_type                  :string(20)
#  fill_by                       :date
#  languages                     :string
#  created_at                    :datetime
#  updated_at                    :datetime
#  require_photo                 :boolean          default(FALSE), not null
#  require_video                 :boolean          default(FALSE), not null
#  compensation_range_low        :decimal(11, 2)
#  compensation_range_high       :decimal(11, 2)
#  expiration                    :datetime
#  custom_practice_software      :string
#  require_resume                :boolean          default(FALSE), not null
#  require_recommendation_letter :boolean          default(FALSE), not null
#

# The core piece of Swiss Monkey - the job posting
class JobPosting < ApplicationRecord
  include EnumerationsHelper
  include LegacyHelper
  include WithExperience
  include WithJobType
  include WithShifts

  belongs_to :job_position
  belongs_to :company
  belongs_to :closed_job_reason, optional: true
  belongs_to :company_location
  has_many :job_applications, dependent: :destroy
  has_many :applications, through: :job_applications, class_name: 'User', dependent: :nullify
  has_many :job_postings_views, dependent: :destroy
  has_many :viewing_users, through: :job_postings_views, class_name: 'User', dependent: :nullify
  has_many :users_job_notifications, dependent: :destroy
  has_many :users_notified, through: :users_job_notifications, class_name: 'User', dependent: :nullify

  has_many :job_postings_practice_management_systems, dependent: :destroy
  has_many :practice_management_systems, through: :job_postings_practice_management_systems, dependent: :nullify
  has_many :job_postings_shift_configurations, dependent: :destroy
  has_many :shift_configurations, through: :job_postings_shift_configurations, dependent: :nullify
  has_many :job_postings_software_proficiencies, dependent: :destroy
  has_many :software_proficiencies, through: :job_postings_software_proficiencies, dependent: :nullify

  scope :by_companies, ->(company_ids) { where company_id: company_ids }

  def created_at_pretty
    created_at.to_formatted_s(:full_date)
  end

  def created_at_mysql_format
    created_at.to_formatted_s(:mysql_date_time_format)
  end

  def closed?
    publication_status == 'CLOSED'
  end

  def published?
    publication_status == 'PUBLISHED'
  end

  def practice_management_systems_names
    practice_management_systems.map(&:software).join(',')
  end

  def compensation_label
    compensation_type&.titleize || 'Not Specified'
  end

  def status_label
    publication_status&.titleize
  end

  def status_legacy
    case publication_status
    when 'UNPUBLISHED'
      1
    when 'PUBLISHED'
      2
    when 'CLOSED'
      3
    end
  end

  def compensation_range?
    compensation_range_low.present? && compensation_range_high.present? && compensation_range_low != 'Not Specified'
  end

  def skills_list
    skills = software_proficiencies.map(&:id)
    SoftwareProficiency.ordered_skills.map do |skill|
      skill.name_with_children(skills)
    end
  end

  def compensation_amount_label
    if compensation_range_low.present? && compensation_range_high.present? && compensation_range_low != 'Not Specified'
      "#{compensation_range_low}-$#{compensation_range_high}"
    else
      '(Not Specified)'
    end
  end

  def saved_status(user)
    user && JobApplication.where(user_id: user.id, job_posting_id: id, application_status: 'SAVED').any?
  end

  def expired?
    expiration.present? && expiration < Time.zone.now
  end

  def shift_for_day?(shift, day_of_week_index)
    day_of_week = days_of_week[day_of_week_index]

    configuration = shift_configurations.find_by(shift_time: shift)
    return false unless configuration

    configuration.shift_days.split(',').include?(day_of_week)
  end

  def rank_key
    "#{id}||#{job_position.name}||#{created_at.to_formatted_s(:mdy_with_time)}"
  end

  def send_new_application_text!
    return unless company.contact_private_number
    message_text = "New application received for #{job_position.name}! " \
                      'Review by signing in to the application (www.swissmonkey.co).'
    SwissMonkey::Sms.send(company.contact_private_number, message_text)
  end

  def best_email
    company.contact_email || company.employer_user&.email
  end
end

swissmonkey-web/app/models/job_postings_view.rb
# == Schema Information
#
# Table name: job_postings_views
#
#  id             :integer          not null, primary key
#  job_posting_id :integer          not null
#  user_id        :integer          not null
#  view_time      :datetime         not null
#  created_at     :datetime
#  updated_at     :datetime
#

# Log of someone viewing a job posting
class JobPostingsView < ApplicationRecord
  belongs_to :job_posting
  belongs_to :user
end

swissmonkey-web/app/controllers/job_postings_controller.rb
# Employer job posting management
class JobPostingsController < AuthenticatedController
  include EnumerationsHelper
  include SortHelper
  include ProximityHelper

  # NOTE: there is some code for the old pushnotificationspool (ported from Laravel) here:
  # https://gist.github.com/nlively/450b617dc76a5a3b45b29194efe11e9c

  before_action :set_closed_job_reasons
  before_action :set_job_posting, only: %i[show edit update destroy publish_job]
  before_action :setup_form, only: %i[new edit update create]
  before_action :company_from_location, only: %i[create update]
  before_action :process_job_closing, only: :update

  # GET /job_postings
  # GET /job_postings.json
  def index
    @job_postings = JobPosting
                    .by_companies(@company_context&.id)
                    .order("#{sort_column} #{sort_direction}")
                    .page(params[:page])
  end

  # GET /job_postings/1
  # GET /job_postings/1.json
  def show; end

  # GET /job_postings/new
  def new
    @job_posting = JobPosting.new

    @check = true
  end

  # GET /job_postings/1/edit
  def edit
    @check = false
  end

  # POST /job_postings
  # POST /job_postings.json
  def create
    @job_posting = JobPosting.new(job_posting_params)
    @job_posting.company = @company
    @job_posting.publication_status = 'PUBLISHED'

    respond_to do |format|
      if @job_posting.save
        format.html { redirect_to @job_posting, notice: 'Job posting was successfully created.' }
        format.json { render :show, status: :created, location: @job_posting }
      else
        format.html { render :new }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_postings/1
  # PATCH/PUT /job_postings/1.json
  def update
    respond_to do |format|
      @job_posting.assign_attributes(job_posting_params)
      @job_posting.company = @company
      if @job_posting.save!
        format.html { redirect_to @job_posting, notice: 'Job posting was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_posting }
      else
        format.html { render :edit }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  def process_job_closing
    return unless params[:action] == 'close'

    @job_posting.publication_status = 'CLOSED'
    @job_posting.closed_job_reason = determine_closed_job_reason
    @job_posting.save!
    respond_with_success('Job has been updated')
    # rescue => ex
    #   Airbrake.notify ex
    #   return respond_with_try_again
  end

  def determine_closed_job_reason
    other_reason = params[:other_reason]
    closed_job_reason = ClosedJobReason.find_by id: params[:closing_reason_id]
    if closed_job_reason&.reason == 'Other' && other_reason.present?
      ClosedJobReason.create! reason: other_reason, private: true
    else
      closed_job_reason
    end
  end

  # DELETE /job_postings/1
  # DELETE /job_postings/1.json
  def destroy
    @job_posting.destroy
    respond_to do |format|
      format.html { redirect_to job_postings_url, notice: 'Job posting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def publish_job
    @job_posting.update! publication_status: 'PUBLISHED', closed_job_reason_id: nil
    redirect_to job_posting_path(@job_posting)
  end

  private

  def setup_form
    company_ids = current_user.companies.map(&:id)

    @extend_free = false # TODO: possibly expand this later
    @practice_locations = CompanyLocation.where(company_id: company_ids)
    @job_positions = JobPosition.order(:name).all
    @practice_management_systems = PracticeManagementSystem.order(:software).all
    @software_proficiencies_top_level = SoftwareProficiency.without_children
    @software_proficiencies_with_children = SoftwareProficiency.with_children
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_job_posting
    id = if params[:job_posting_id]
           params[:job_posting_id]
         else
           params[:id]
         end

    @job_posting = JobPosting.by_companies(current_user.companies).find_by(id: id)

    redirect_to(root_path) unless @job_posting
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def job_posting_params
    params.require(:job_posting).permit(
      :job_position_id, :job_description,
      :closed_job_reason_id, :skype_interview,
      :company_id, :logo,
      :company_location_id, :compensation_type,
      :publication_status, :years_experience,
      :job_type, :payment_type, :fill_by,
      :languages, :require_photo, :require_video,
      :compensation_range_low, :compensation_range_high,
      :expiration, :custom_practice_software,
      :require_resume, :require_recommendation_letter
    )
  end

  def set_closed_job_reasons
    @closed_job_reasons = ClosedJobReason.universal.order(:reason)
  end

  def company_from_location
    @company = CompanyLocation.find(params[:job_posting][:company_location_id]).company
  end
end

swissmonkey-web/app/controllers/super_admin/job_postings_controller.rb
module SuperAdmin
  # super admin management of job postings
  class JobPostingsController < SuperAdminController
    before_action :set_job_posting, only: %i[show edit update destroy]

    # GET /job_postings
    # GET /job_postings.json
    def index
      @job_postings = JobPosting.all
    end

    # GET /job_postings/1
    # GET /job_postings/1.json
    def show; end

    # GET /job_postings/new
    def new
      @job_posting = JobPosting.new
    end

    # GET /job_postings/1/edit
    def edit; end

    # POST /job_postings
    # POST /job_postings.json
    def create
      @job_posting = JobPosting.new(job_posting_params)

      respond_to do |format|
        if @job_posting.save
          format.html { redirect_to @job_posting, notice: 'Job posting was successfully created.' }
          format.json { render :show, status: :created, location: @job_posting }
        else
          format.html { render :new }
          format.json { render json: @job_posting.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /job_postings/1
    # PATCH/PUT /job_postings/1.json
    def update
      respond_to do |format|
        if @job_posting.update(job_posting_params)
          format.html { redirect_to @job_posting, notice: 'Job posting was successfully updated.' }
          format.json { render :show, status: :ok, location: @job_posting }
        else
          format.html { render :edit }
          format.json { render json: @job_posting.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /job_postings/1
    # DELETE /job_postings/1.json
    def destroy
      @job_posting.destroy
      respond_to do |format|
        format.html { redirect_to job_postings_url, notice: 'Job posting was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_job_posting
      @job_posting = JobPosting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_posting_params
      params.fetch(:job_posting, {})
    end
  end
end

swissmonkey-web/app/views/job_postings/_close_reason_modal.html.erb
<script>
  $(document).ready(function () {
    var jobId;

    $(".close").on('click', function () {
      window.location.reload();
    });

    $(".status_change").click(function () {
      jobId = $(this).attr('atr');
    });

    $(".other_reason").hide();

    $("input[name*='closing_reason_id']").click(function () {
      if ($(this).attr('id') === 'Other')
        $(".other_reason").show();
      else
        $(".other_reason").hide();
    });

    $.validator.addMethod("feedback_required", function (value) {
      var n = $('input:radio[name^="closing_reason_id"]:checked').length;
      return (n > 0);
    }, 'Please provide your feedback.');

    $.validator.addMethod('valid_format', function (value) {
      value = value.replace(/\s+/g, ' ');
      if (value === '') {
        return true;
      }
      return (value.match(/^[a-zA-Z() ]+$/));
    }, "");

    $("#job_closing_form").validate({
      rules: {
        closing_reason_id: {
          feedback_required: true
        },
        other_reason: {}
      },
      messages: {
        closing_reason_id: {
          feedback_required: "*Required"
        },
        other_reason: {
          valid_format: "Invalid"
        }
      },
      errorPlacement: function (error, element) {
        var name = $(element).attr("name");
        error.appendTo($("#" + name + "_validate"));
      },
      submitHandler: function (form) {
        $.ajax({
          url: "/jobs/" + jobId + '?action=close',
          type: 'PUT',
          data: $('#job_closing_form').serialize(),
          success: function () {
            window.location.reload();
          },
          error: function (xhr, status, error) {
            return false;
          }
        });
      }
    });


  });
</script>
<div class="modal fade" id="close-job-modal" role="dialog" style="margin-top: 10%;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Provide us more information</h4>
      </div>
      <form method="post" name="job_closing_form" id="job_closing_form">
        <div class="modal-body">
          <span id='job_closed_validate' class="error_custom_display1"></span><br>
          <% @closed_job_reasons.each do |status| %>
            <label>
              <%= radio_button_tag :closing_reason_id, status.id %>
              <%= status.description %>
            </label>
            <br>
          <% end %>
          <div class="other_reason" style="margin-top: 20px;">
            <div class="group group-pad">
              <input type="text" class="material-input" name="other_reason"
                     required/>
              <span class="bar"></span>
              <label>ENTER REASON </label>
              <span id='reason_validate' class="error_custom_display"></span>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="submit" id="modal-close" class="btn btn-default">Close</button>
        </div>
      </form>
    </div>

  </div>
</div>

swissmonkey-web/app/views/job_postings/_confirm_modal.html.erb
<div class="modal fade" id="msgModal" role="dialog">
  <div class="modal-dialog modal-md alert-modal">
    <div class="modal-content">
      <div class="modal-body">
        <p class="modal-message"></p>
      </div>
      <div class="modal-footer">
        <button type="button" id="modal-activate" class="btn btn-default jobslist">
          <a href="#">Ok</a>
        </button>
      </div>
    </div>
  </div>
</div>

swissmonkey-web/app/views/job_postings/_delete_card_confirmation_modal.html.erb
<div class="modal fade" id="delete-card-modal" role="dialog">
  <div class="modal-dialog modal-md alert-modal">
    <div class="modal-content">
      <div class="modal-body">
        <p class="modal-message">Do you want to delete your card details?</p>
      </div>
      <div class="modal-footer">
        <button type="button" id="modal-activate" data-dismiss="modal" class="btn btn-default"><a
        href="#">No</a></button>
        <button type="button" id="modal-activate" class="btn btn-default delete-card"><a href="#">Delete</a>
        </button>
      </div>
    </div>
  </div>
</div>

swissmonkey-web/app/views/job_postings/_discount_applied_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel" id="congoModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header" style="border:0;">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>

      </div>
      <div class="modal-body">
        <div class="my-congrats text-center">
          <%= image_tag 'congratulations-icon.png', alt: 'congratulations-icon' %>
          <h2>Congratulations!</h2>
          <p>You have got <span>100% discount!</span></p>
        </div>
      </div>
      <div class="modal-footer" style="text-align:center !important; border:0;">
        <p>Note: Posting lasts for 30 days</p>
        <button type="button" class="btn btn-default cancel-coupon" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary submitBtn" id="congoJob">Publish Job</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

swissmonkey-web/app/views/job_postings/_fill_profile_prompt_modal.html.erb
<div class="modal fade" id="alert-modal" role="dialog">
  <div class="modal-dialog modal-md alert-modal">
    <div class="modal-content">
      <div class="modal-body">
        <p>Please fill your profile</p>
      </div>
      <div class="modal-footer">
        <%= link_to edit_company_path(@company) do %>
          <button type="button" class="btn btn-default">Ok</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

swissmonkey-web/app/views/job_postings/_save_card_error_modal.html.erb
<div class="modal fade" id="save-card-error" role="dialog">
  <div class="modal-dialog modal-md alert-modal">
    <div class="modal-content">
      <div class="modal-body">
        <p class="modal-message save-card-error-message"></p>
      </div>
      <div class="modal-footer">
        <button type="button" id="modal-activate" data-dismiss="modal" class="btn btn-default close-no"><a
        href="#">Ok</a></button>
      </div>
    </div>
  </div>
</div>

swissmonkey-web/app/views/job_postings/edit.html.erb
<%= render 'form', job_posting: @job_posting %>

swissmonkey-web/app/views/job_postings/index.html.erb
<div id="wrapper">
  <div id="page-wrapper">
    <div class="contener-main" style="background: none;">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 view-jobs">
        <div class="row">

          <% if @job_postings.empty? %>
            <div class="no-applicants">
              <img src="<%= image_tag 'images/no-applicants.png' %>" alt="applicants"/>
              <div class="clear"></div>
              <p><strong>You have no jobs Posted yet.<br/>
                Please post a job. </strong>
              </p>
            </div>
          <% else %>
            <div class="table-000">
              <table width="100%" border="0" cellspacing="0" cellpadding="0" class="border-bottom">
                <thead>
                <tr class="job-list-head">
                  <th width="10%" valign="top">
                    <%= sort_link 'created_at', 'Date Posted' %>
                  </th>
                  <th width="15%" valign="top">
                    Practice Address
                  </th>
                  <th width="20%" valign="top">
                    Position
                  </th>
                  <th width="10%" valign="top">
                    Job Type
                  </th>
                  <th width="10%" valign="top">
                    Applicants
                  </th>
                  <th width="15%" valign="top">
                    Status
                  </th>
                </tr>

                </thead>
                <tbody style="background: #fff;">
                <% @job_postings.each do |job| %>
                  <tr>
                    <td width="10%" valign="middle"><%= job.created_at_pretty %></td>
                    <td width="15%" valign="middle">
                      <%= job.company&.name %><br>
                      <%= job.company_location&.to_s %>
                    </td>
                    <td width="20%" valign="middle"><%= job.job_position&.name %></td>
                    <td width="10%" valign="middle"><%= job.job_type_label %></td>
                    <td width="10%" valign="middle">
                      <%= link_to applicants_path(company_id: job.company_id, job_posting_id: job.id) do %>
                        <button class="btn btn-default view-applicants">
                          <%= job.job_applications.count %> Applicants
                        </button>
                      <% end %>
                    </td>
                    <td width="15%" valign="middle">

                      <div class="dropdown">

                        <div class="group">
                          <button type="button"
                                  class="group btn btn-default dropdown-toggle status_change"
                                  aria-expanded="true"
                                  attr="<%= job.id %>" data-toggle="dropdown"
                                  aria-haspopup="true"
                                  style="margin-bottom: 0px;">
                            <%= job.status_label %><span class="caret"></span>
                          </button>
                          <ul class="dropdown-menu open" aria-expanded="false"
                              style="min-width:120px">
                            <% unless job.closed? %>
                              <li>
                                <a href="#" data-toggle="modal"
                                   data-target="#close-job-modal"
                                   id="status_drop_down"
                                   atr="<%= job.id %>"> Closed
                                </a>
                              </li>
                            <% end %>
                            <li>
                              <%= link_to edit_job_posting_path(job) do %>
                                <%= job.published? ? 'Unpublished' : 'Published' %>
                              <% end %>
                            </li>
                          </ul>
                        </div>
                      </div>
                      <a href="<%= edit_job_posting_path(job) %>" class="right-arrow">
                        <%= image_tag 'right-arrow.png', alt: 'View/edit job posting' %>
                      </a>
                    </td>
                  </tr>
                <% end %>
                </tbody>
              </table>
            </div>
            <%= paginate @job_postings, param_name: :page %>
          <% end %>
        </div>
      </div>
    </div>
    <%= render 'close_reason_modal' %>

    <div class="clear"></div>
  </div>
</div>

swissmonkey-web/app/views/job_postings/new.html.erb
<%= render 'form', job_posting: @job_posting %>

swissmonkey-web/app/views/job_postings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_job_posting_path(@job_posting) %> |
<%= link_to 'Back', job_postings_path %>