swissmonkey-web/config/routes.rb
Rails.application.routes.draw do
  get 'subscription/summary'
  get 'notification/count'
  get 'notification/change_count'
  get 'notification/mark_read'

  get 'api_test' => 'application#api_test'

  namespace :api do
    namespace 'v1', path: 'v1.0' do # as v1.0', controller: 'v1', as: 'v1' do
      get 'dropdown/data', action: 'datasets'

      namespace :user do
        post 'signup'
        post 'login'
        post 'logout'
        post 'forgot'
        post 'reset'
        post 'validate'
        post 'deactivate'
        post 'activate'
        post 'deviceregistration', action: 'device_registration'
        post 'accept_privacy_policy'
        post 'privacy_policy_status'
      end

      namespace :job do
        post 'details/:id', action: 'details'
        post 'search'
        post 'save'
        post 'apply'
        post 'jobs'
        post 'applications'
        post 'savedjobs'
        post 'history'
      end

      namespace :profile do
        post 'save'
        post 'upload'
        post 'download'
        post 'info'
        post 'delete'
      end

      namespace :settings do
        post 'apinotifications'
        post 'update'
        post 'viewed'
      end
    end
  end

  namespace :authentications do
    get 'facebook'
    get 'google'
    get 'linkedin'
  end

  namespace :stripe do
    post 'apply_coupon'
    post 'delete_card'
    post 'check_location_payment'
  end

  resources :applicants # , only: :index
  resources :companies do
    post 'set_current_context'
  end
  resources :job_postings
  get 'profile/me' => 'profiles#me', as: 'my_profile'
  resources :profiles
  resource :account, controller: 'account' do
    get 'verify_email_change'
    post 'set_current_company/:id', action: 'set_current_company', as: 'set_current_company'
  end
  resource :subscription

  get 'super_admin' => 'super_admin#index'
  namespace :super_admin do
    resources :companies
    resources :job_postings
    resources :users
  end

  devise_for :admins
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/auth/facebook/callback' => 'authentications#facebook'
  get '/auth/google_oauth2/callback' => 'authentications#google'
  get '/auth/linkedin/callback' => 'authentications#linkedin'

  # legacy paths
  match 'publishJob/:id' => 'job_postings#publish_job', via: %i[get post]
  match 'accountSettings' => 'profile#account_settings', via: %i[get post]
  match 'alertnotification' => 'profile#alert_notification', via: %i[get post]

  root 'home#index'
end

swissmonkey-web/app/views/layouts/_admin_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span>
      <span class="icon-bar"></span></button>
    <%= link_to 'Swiss Monkey', job_postings_path, class: 'navbar-brand' %>
  </div>

  <%= render 'layouts/welcome' %>

  <ul class="nav navbar-right top-nav">

    <li class="dropdown" id="notifications-div">
      <a href="#" class="dropdown-toggle user-alert-li" data-toggle="dropdown">
        <%= image_tag 'user_icon.png' %>
        <span class="user-alert notifications_div"></span>
      </a>

      <ul class="dropdown-menu alert-dropdown" id="applicants_list">
      </ul>
    </li>

  </ul>

  <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <%= image_tag 'images/btm-logo.png', width: '70px', height: '70px' %>
    <h4></h4>

    <%= render_navigation(expand_all: true, level: 2..4, renderer: :bootstrap, &super_admin_menu_items) %>

    <!-- /.navbar-collapse -->
    <div class="logo-info">
      <%= image_tag 'images/logo.png', alt: 'SwissMonkey' %>
      <p>All rights reserved 2016-<%= Date.year %> @SwissMonkey</p>
    </div>
    <div class="sidebar-pattern">
      <%= image_tag 'images/pattern2.png', alt: 'pattern' %>
    </div>
  </div>

</nav>

swissmonkey-web/app/views/layouts/_form_errors.haml
- if model.errors.any?
  .alert.alert-danger#error_explanation
    %p
      = pluralize(model.errors.count, 'error')
      prohibited the form from being saved:
    %ul
      - model.errors.full_messages.each do |msg|
        %li= msg

swissmonkey-web/app/views/layouts/_messages.haml
%aside#alerts
  - flash.each do |name, msg|
    - alert_subclass = { notice: :info, alert: :warning, error: :danger }[name.to_sym] || name
    - if msg.is_a?(String)
      .alert{ class: "alert-#{alert_subclass}" }
        %button.close{ type: 'button', data: { dismiss: 'alert' } }
          &times;
        = msg

swissmonkey-web/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span>
      <span class="icon-bar"></span></button>
    <%= link_to 'Swiss Monkey', job_postings_path, class: 'navbar-brand' %></div>

  <div class="pull-left">
    <%= render 'layouts/welcome' %>
  </div>
  <ul class="nav navbar-nav navbar-right">
    <% if current_user&.employer? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= image_tag 'ger-icon.png', alt: 'user' %></a>
        <ul class="dropdown-menu">
          <li class="icon-drop"></li>
          <li>
            <%= link_to companies_path do %>
              <i class="fa fa-fw fa-user"></i> Profile
            <% end %>
          </li>
          <li>
            <%= link_to account_path do %>
              <i class="fa fa-fw fa-gear"></i> Settings
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-fw fa-sign-out"></i> Sign Out
            <% end %>
          </li>
        </ul>
      </li>

      <li class="dropdown" id="subscriptionNotification">

      </li>
    <% end %>
    <li class="dropdown" id="notifications-div">
      <a href="#" class="dropdown-toggle user-alert-li" data-toggle="dropdown">
        <%= image_tag 'user_icon.png', alt: 'user' %>

        <span class="user-alert notifications_div">
                                </span>


      </a>

      <ul class="dropdown-menu alert-dropdown" id="applicants_list">
      </ul>
    </li>

    <% if current_user&.employer? %>
      <li>
        <%= link_to new_job_posting_path do %>
          <button class="btn postajob"><strong>Post a Job</strong></button>
        <% end %></li>
    <% end %>
  </ul>
</nav>

swissmonkey-web/app/views/layouts/_sidebar.html.erb
<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
<div class="collapse navbar-collapse navbar-ex1-collapse">

  <% path = current_user&.employer? ? my_profile_path : '#' %>
  <%= link_to path do %>
    <div class="admin-pic">
      <% if current_user&.profile_pic? && current_user&.employer? %>
        <%= image_tag current_user.profile_pic %>
      <% elsif current_user&.employer? %>
        <%= image_tag 'DefaultPhotoIcon@3x.1.png', class: 'img-circle' %>
        <%= image_tag 'btm-logo.png' %>
      <% end %>
      <% if current_user&.employer? %>
        <p style="margin-top: 22px"><%= current_user&.name %></p>
      <% end %>
    </div>
  <% end %>

  <%= render_navigation(expand_all: true, level: 2..4, renderer: :bootstrap, &left_navigation_menu_items) %>


  <div class="sidebar-pattern">
    <%= image_tag 'images/pattern2.png', alt: 'pattern' %>
  </div>
</div>

swissmonkey-web/app/views/layouts/_welcome.html.erb
<% if user_signed_in? %>
  <div class="top-title admin-title">Welcome
    <strong>
      <%= current_user.name %>
    </strong>

    <% if @notification_count %>
      , You have
      <%= $notificationCount %>notifications
    <% end %>
  </div>
<% end %>

swissmonkey-web/app/views/layouts/application.html.erb
<html>
<head>
  <title><%= full_head_title %></title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <%= javascript_include_tag 'application' %>

  <script>
    Stripe.setPublishableKey('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');

    $(document).ready(function () {
      $("#notifications-div").on("click", function (event) {
        $.get('<%= notification_change_count_url %>'.js);
      });
      $('#loader-overlay').hide();
      <% if current_user&.employer? %>
      $.get('<%= subscription_summary_url %>.js');
      <%  end %>
      $.get('<%= notification_count_url %>.js');
    });
    setInterval(function (e) {
      $.get('<%= notification_count_url %>.js');
    }, 10000);
  </script>
  <style>
    #activePostJob {
      color: #553e70 !important;
    }

    .postajob {
      background: #489EAB;
      border: 1px solid #553e70;
    }

    .postajob:hover, .postajob:focus {
      color: #553e70;
      text-decoration: none;
    }

    .spancount {
      margin-left: 6px;
      font-weight: bold;
    }
  </style>
</head>
<body data-signed-in="<%= user_signed_in? ? 'true' : 'false' %>"
      data-terms-agreed="<%= current_user&.accepted_terms? ? 'true' : 'false' %>"
      data-user-email="<%= current_user&.email %>">

<div id="loader-overlay">
  <%= image_tag 'ajax-loader-spinner.gif', id: 'loader' %>
  <div id="loadingProgressG">
    <div id="loadingProgressG_1" class="loadingProgressG">
    </div>
  </div>
</div>
<%= render 'layouts/navbar' %>
<div id="page-container" class="container">
  <div class="row">
    <div class="col-sm-2">
      <%= render 'layouts/sidebar' %>
    </div>
    <div class="col-sm-10">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </div>

  <%= render 'shared/terms_modal' %>
</div>

<footer>
  <div class="container">
    <div class="logo-info">
      <%= image_tag 'images/logo.png', alt: 'SwissMonkey', class: 'pull-left' %>
      <p>All rights reserved 2016-<%= Date.today.year %> @SwissMonkey</p>
      <p> User ID: <%= current_user&.id %> <%= current_user&.email %></p>
    </div>
  </div>
</footer>

</body>
</html>

swissmonkey-web/app/views/layouts/application.html.haml
<!DOCTYPE html>
%html

  %head
    %meta{ charset: 'utf-8' }
    %meta{ http_equiv: 'X-UA-Compatible', content: 'IE=edge' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    .container
      = render 'layouts/messages'
      = yield

swissmonkey-web/app/views/layouts/super_admin.html.haml
%html

  %head
    %title= admin_head_title
    = csrf_meta_tags
    = stylesheet_link_tag 'super_admin'
    = javascript_include_tag 'application'

  %body
    %nav.navbar.navbar-inverse.navbar-static-top
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{ type: 'button',
              'data-toggle': 'collapse',
              'data-target': '#navbar-collapse',
              'aria-expanded': 'false' }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{ href: '/super_admin' } Admin Tools
        .collapse.navbar-collapse#navbar-collapse
          = render_navigation(expand_all: true,
              level: 2..4, renderer: :bootstrap,
              &super_admin_menu_items)

    .container
      = render 'layouts/messages'
      - if @page_title.present?
        %h1= @page_title

      = yield